# Generated by Django 5.2.12 on 2026-04-07 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_api', '0004_coursetopic_planner_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetopic',
            name='expectations',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
