# Generated by Django 5.2.12 on 2026-04-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_api', '0007_question_first_course_engine'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursequestion',
            name='example_answer',
            field=models.TextField(blank=True, default=''),
        ),
    ]
