# Generated by Django 5.2.12 on 2026-04-18 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_api', '0008_coursequestion_example_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginRateLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_key', models.CharField(max_length=255)),
                ('client_identifier', models.CharField(max_length=255)),
                ('failed_attempt_timestamps', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('username_key', 'client_identifier', 'id'),
                'constraints': [models.UniqueConstraint(fields=('username_key', 'client_identifier'), name='chat_api_login_rate_limit_unique_identity')],
            },
        ),
    ]
