"""
Django settings for agentic_curiosity project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from .env import env_bool, env_int, env_list, load_env_file

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_env_file(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-8r(fg0t0^4*c0st8zhq1i%o8xvjsy5^*o9ov2wan=&xw)oafra',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DJANGO_DEBUG', default=True)

ALLOWED_HOSTS = env_list('DJANGO_ALLOWED_HOSTS', default=[])
OPENAI_API_KEY = os.environ.get('OPENAI_API_KEY')
OPENAI_ORGANIZATION = os.environ.get('OPENAI_ORGANIZATION')
OPENAI_PROJECT = os.environ.get('OPENAI_PROJECT')
OPENAI_BASE_URL = os.environ.get('OPENAI_BASE_URL')
AI_CHAT_MODEL = os.environ.get('AI_CHAT_MODEL')
AI_CHAT_ANSWERER_MODEL = os.environ.get('AI_CHAT_ANSWERER_MODEL')
AI_CHAT_PLANNER_MODEL = os.environ.get('AI_CHAT_PLANNER_MODEL')
AI_CHAT_BRIEFER_MODEL = os.environ.get('AI_CHAT_BRIEFER_MODEL')
AI_CHAT_CONTEXT_THRESHOLD_BYTES = env_int('AI_CHAT_CONTEXT_THRESHOLD_BYTES', default=5_120)
AI_CHAT_RECENT_TURNS_TO_KEEP = env_int('AI_CHAT_RECENT_TURNS_TO_KEEP', default=10)
AI_CHAT_MODEL_RECENT_TURNS = env_int('AI_CHAT_MODEL_RECENT_TURNS', default=4)
AI_CHAT_LOG_LEVEL = os.environ.get('AI_CHAT_LOG_LEVEL', 'INFO')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core.apps.CoreConfig',
    'ai_chat.apps.AiChatConfig',
    'chat_api.apps.ChatApiConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'agentic_curiosity.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'agentic_curiosity.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '[{asctime}] {levelname} {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'standard',
        },
    },
    'loggers': {
        'ai_chat': {
            'handlers': ['console'],
            'level': AI_CHAT_LOG_LEVEL,
            'propagate': False,
        },
    },
}
