# Generated by Django 5.2.12 on 2026-04-07 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_chat', '0002_chatcontext_session_context'),
        ('chat_api', '0002_coursetopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='course_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='chat_api.coursetopic'),
        ),
    ]
