# Generated by Django 5.2.12 on 2026-04-07 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_chat', '0005_chatcontext_created_at_chatturn_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='course_state',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
