# Generated by Django 5.2.12 on 2026-04-12 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_chat', '0008_question_first_runtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionattempt',
            name='interaction_type',
            field=models.CharField(choices=[('hint_request', 'Hint Request'), ('answer_attempt', 'Answer Attempt'), ('skip', 'Skip'), ('full_answer_request', 'Full Answer Request')], max_length=20),
        ),
    ]
