# Generated by Django 5.2.12 on 2026-04-18 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_chat', '0009_alter_questionattempt_interaction_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerPhotoUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_key', models.CharField(max_length=500, unique=True)),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('byte_size', models.PositiveIntegerField()),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('extracted_text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo_uploads', to='ai_chat.questionattempt')),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_photo_uploads', to='ai_chat.questionpresentation')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_photo_uploads', to='ai_chat.chatsession')),
            ],
            options={
                'ordering': ('presentation_id', 'display_order', 'id'),
            },
        ),
    ]
